### ISSUE TITLE
2.3.5 crashing

### ISSUE THREAD

**Issue by dtomcat** [MakeMHz/xenium-fw-update#7]
Xbox 1.6, 
Xenium Ice 2.3.1, 
M8Plus_16 bios.  
kernel: 1.00.5838.01

Put recovery.bin in E: root.   Ran from M8 bios as well as avalaunch, both crash back to M8plus home screen.

**Comment by LoveMHz** [comment]
Sorry, but I'm a bit confused. Is the updater crashing?

**Comment by dtomcat** [comment]
M8 goes to loading screen, but never see updater and goes back to main dashboard screen

**Comment by dtomcat** [comment]
Previous version loads

**Comment by LoveMHz** [comment]
Interesting. It might be an issue with nxdk.

Can you delete the files from the Xbox and try transferring it again? Just to rule out a corrupt transfer.

**Comment by dtomcat** [comment]
Will do

**Comment by dtomcat** [comment]
ok.. transferred over again after fresh download.  didn't work.  try avalaunch, didn't work.... tried file manager from avalaunch.. didn't work (all of these are the same file but renamed to default.xbe... try launching with original name (from file manager in avalaunch.  it worked!  however, I still run into same problem of xenium not detected.  (reminder that it was detected on 2.2.1, but not after I update to 2.3.1... downgrading back to 2.2.1, xenium detected... back to 2.3.1 and not detected again)

But for this issue, you can't rename the xbe.  sorry for adding the issue.
